### ISSUE TITLE
Document alternative development setup

### ISSUE THREAD

**Issue by fwolfst** [brentkearney/workshops#4]
I wanted to have a look at the application (couldnt find a demo somewhere). Due to slow internet connectivity and and other reasons (like working in `/tmp` directory and not caring about cleaning up after experiments) here, I prefer a simple `sqlite3` setup over Docker setup.

I managed to arrive at a log-in page, running ruby 2.6.1 and a sqlite3 database. However, it seems that it needs some trickery.

Does it make sense if I file some issues here about what fails (like I had to change `Settings.Site['title']` to `Settings.Site[:title]` which is probably independent of my experiments)? Is the master branch up for this kind of experimentation at the moment? Do the instructions for Docker setup work (again, living in remote Germany, setting it up would make me use up precious bandwidth and have me initially test my patience)?

Or (favorite solution :) ), could you set up a demo site somewhere?

Appreciating your efforts.

**Comment by brentkearney** [comment]
Yes, please report issues you have -- I would be happy to address them. I'm sorry the onramp is rather steep; it has been awhile since I've set it up from scratch.

That's a good idea, to set up a demo site. I will look into it. I also really need to generate a substantial database seed file, populated with fake data. 

I just noticed that I didn't mention seeding anywhere: `rake db:seed`. The db/seeds.rb file doesn't contain much, but it provides one event record, with a default schedule.

That is odd about the Settings.Site symbol vs string key, because they are stored in the database as strings, and the Settings web interface will convert symbols to strings before saving. Was `rake ws:init_settings` failing?

As per step 4 of the README, default login information is in the lib/tasks/ws.rake file. It should have been executed by the entrypoint.sh script: `rake ws:create_admins RAILS_ENV=development`.

**Comment by fwolfst** [comment]
Yah, about the `Setting.Site`; that was probably my bad. The rake task and also creation via `rails console` did not succeed, so I hacked around until I had something working. I guess that I populated the settings itself with symbols instead of strings.

**Comment by fwolfst** [comment]
Basically, I got the setup working. There is a `OVERLAPS` statement in `schedule_helper` which I believe is easy to fix. Tell me if I should make a PR (https://github.com/ecovillage/workshops/tree/4_readme-sqlite).

**Comment by brentkearney** [comment]
Excellent! Thanks so much for working on it. Yes, make a PR, I will merge it.

I tried to get a demo version of Workshops running in production mode up and running last night, but ran into some obscure issue with http_parser and the rugged gem, both compiled on the same VPS, but seemingly incompatible with each other. Will work more on that soon.

**Comment by fwolfst** [comment]
omg, sorry for the messy git history, I am still confused that the commits show up here. In the pull request they are clean though.
